source ('010-settings.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('030-good.functions.R',echo = TRUE, max.deparse.length = Inf)
source ('035-download.R',echo = TRUE, max.deparse.length = Inf)
source ('040-create_schema.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('050-create_early_indexes.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('060-clinical.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('070-rna.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('080-geography.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('090-exongeo.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('100-exonrna.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('110-cnv.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('120-cnc.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('125-rppa.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('130-mut.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('135-viral.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('140-urna.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('150-pcgeneprogram.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('160-rabit.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('170-hrd.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('180-immunescore.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('190-molecsubtype.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('200-immunemodel.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('210-fmut.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('220-cnvsegments.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('230-clinpheno.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('240-allprobetable.R',echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('250-create_views.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('255-cohorts_table.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('300-final_indexing.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('260-tmb.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('270-estimate.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
## add_signatures_to_db.R will break with small tests, so do this near the end
source ('280-add_signatures_to_db.R', echo = TRUE, max.deparse.length = Inf)
source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
source ('290-record_environment.R', echo = TRUE, max.deparse.length = Inf)
## source ('020-database_connection.R', echo = TRUE, max.deparse.length = Inf)
## source ('310-optimize.R', echo = TRUE, max.deparse.length = Inf)


sessionInfo()
