################################################################
## Type descriptions, references, and examples for the types table
## Sourced by the build pipeline to enrich the types table

type_info = data.frame(
  type = c(
    "rna", "cnv", "cnc", "rppa", "mut", "viral", "urna",
    "pc_gene_program", "rabit", "hrd", "immune_score",
    "molec_subtype", "immune_subtype", "fmut", "muttest",
    "tmb", "estimate", "msi", "sig"
  ),
  description = c(
    "Batch-effect normalized (EB++) Illumina HiSeq RNA-seq V2 gene-level expression (log2 RSEM)",
    "Gene-level copy number from SNP6 arrays (log2 ratio, copy number / 2)",
    "GISTIC2 thresholded copy number calls: -2 (homdel), -1 (hemdel), 0 (neutral), 1 (gain), 2 (amp)",
    "Reverse phase protein array (RPPA) normalized protein expression (~200 antibodies)",
    "Binary gene-level non-silent somatic mutation status (1 = mutated) from MC3 pipeline",
    "Log2-transformed viral transcript read counts detected in tumor RNA-seq",
    "Batch-effect adjusted microRNA expression from Illumina GA/HiSeq platforms",
    "Gene program activity scores (drug targets, canonical pathways) from PanCan12 projected onto PanCan33",
    "Transcription factor activity scores inferred by the RABIT algorithm from RNA-seq",
    "Homologous recombination deficiency scores and components (LOH, TAI, LST) from SNP6 arrays",
    "68 immune and microenvironment gene expression signature scores",
    "Curated molecular subtype assignments for 33 cancer types (e.g., Basal, LumA, CIN)",
    "Model-based immune subtypes C1-C6 (wound healing, IFN-gamma, inflammatory, etc.)",
    "Positional mutation annotations with amino acid change and effect (e.g., TP53_R175H_Missense)",
    "Binary indicator: was this sample exome-sequenced in the MC3 pipeline",
    "Log10-transformed count of non-silent somatic mutations per sample",
    "ESTIMATE algorithm scores: StromalScore, ImmuneScore, ESTIMATEScore, TumorPurity",
    "MSIsensor microsatellite instability score (0 = stable, higher = more unstable)",
    "Custom gene expression signatures (immune cell types: TCD8, Treg, NK, B cell, etc.)"
  ),
  example = c(
    "CD8A, FOXP3, TP53 (no suffix)",
    "CDKN2A.cnv, EGFR.cnv",
    "CDKN2A.cnc, TP53.cnc (values: -2,-1,0,1,2)",
    "AKT.rppa, HER2.rppa",
    "TP53.mut, KRAS.mut (values: 0 or 1)",
    "EBV.viral, HPV.viral",
    "hsa-miR-21-5p.urna",
    "GP1_Proliferation/DNA_repair.pc_gene_program",
    "FOXP3.rabit, NFATC1.rabit",
    "hrd-loh.hrd, lst1.hrd",
    "LIexpression_score.immune_score, Chemokine12_score.immune_score",
    "Subtype_Selected.molec_subtype (values: BRCA.LumA, GI.CIN, etc.)",
    "Subtype_Immune_Model_Based.immune_subtype (values: C1-C6)",
    "TP53.fmut (values: TP53_p.R175H_Missense_Mutation, etc.)",
    "muttest.muttest (value: 1 if exome-sequenced)",
    "tmb (no suffix, single probe)",
    "StromalScore.estimate, ImmuneScore.estimate",
    "MSIsensor_score.msi",
    "TCD8.sig, Treg.sig, NK.sig"
  ),
  reference = c(
    "Hoadley et al. 2018, Cell 173(2):291-304. PMID:29625048",
    "Hoadley et al. 2018, Cell 173(2):291-304. PMID:29625048",
    "Mermel et al. 2011, Genome Biology 12:R41. PMID:21527027",
    "Akbani et al. 2014, Nat Commun 5:3887. PMID:24871328",
    "Ellrott et al. 2018, Cell Systems 6(3):271-281. PMID:29596782",
    "Thorsson et al. 2018, Immunity 48(4):812-830. PMID:29628290",
    "Hoadley et al. 2018, Cell 173(2):291-304. PMID:29625048",
    "Hoadley et al. 2014, Cell 158(4):929-944. PMID:25109877",
    "Jiang et al. 2015, PNAS 112(24):7511-7516. PMID:26034287",
    "Knijnenburg et al. 2018, Cell Reports 26(2):525-537. PMID:30625304",
    "Thorsson et al. 2018, Immunity 48(4):812-830. PMID:29628290",
    "Hoadley et al. 2018, Cell 173(2):291-304. PMID:29625048",
    "Thorsson et al. 2018, Immunity 48(4):812-830. PMID:29628290",
    "Ellrott et al. 2018, Cell Systems 6(3):271-281. PMID:29596782",
    "Ellrott et al. 2018, Cell Systems 6(3):271-281. PMID:29596782",
    "Derived from MC3 fmut counts. Ellrott et al. 2018. PMID:29596782",
    "Yoshihara et al. 2013, Nat Commun 4:2612. PMID:24113773",
    "Knijnenburg et al. 2018, Cell Reports 26(2):525-537. PMID:30625304",
    "Custom signatures from RNA-seq. Hoadley et al. 2018. PMID:29625048"
  ),
  source_file = c(
    "EB++AdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.xena.gz",
    "broad.mit.edu_PANCAN_Genome_Wide_SNP_6_whitelisted.gene.xena.gz",
    "TCGA.PANCAN.sampleMap__Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes.gz",
    "TCGA-RPPA-pancan-clean.xena.gz",
    "mc3.v0.2.8.PUBLIC.nonsilentGene.xena.gz",
    "GDC download (UUID a55229b3)",
    "pancanMiRs_EBadjOnProtocolPlatformWithoutRepsWithUnCorrectMiRs_08_04_16.xena.gz",
    "Pancan12_GenePrograms_drugTargetCanon_in_Pancan33.tsv.gz",
    "RABIT__pancan__RABIT_pancan.HiSeq.V2.gz",
    "TCGA.HRD_withSampleID.txt.gz",
    "TCGA_pancancer_10852whitelistsamples_68ImmuneSigs.xena.gz",
    "TCGASubtype.20170308.tsv.gz",
    "Subtype_Immune_Model_Based.txt.gz",
    "mc3.v0.2.8.PUBLIC.xena.gz",
    "Derived from MC3 sample list",
    "Computed from fmut counts (260-tmb.R)",
    "ESTIMATE_copy.csv (precomputed)",
    "Knijnenburg_TableS5_MSIsensor.xlsx",
    "Computed at build time (280-add_signatures_to_db.R)"
  ),
  source_url = c(
    "https://xenabrowser.net/datapages/?dataset=EB%2B%2BAdjustPANCAN_IlluminaHiSeq_RNASeqV2.geneExp.xena&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=broad.mit.edu_PANCAN_Genome_Wide_SNP_6_whitelisted.gene.xena&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=TCGA.PANCAN.sampleMap/Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=TCGA-RPPA-pancan-clean.xena&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=mc3.v0.2.8.PUBLIC.nonsilentGene.xena&host=https://pancanatlas.xenahubs.net",
    "",
    "https://xenabrowser.net/datapages/?dataset=pancanMiRs_EBadjOnProtocolPlatformWithoutRepsWithUnCorrectMiRs_08_04_16.xena&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=Pancan12_GenePrograms_drugTargetCanon_in_Pancan33.tsv&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=RABIT/pancan/RABIT_pancan.HiSeq.V2&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=TCGA.HRD_withSampleID.txt&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=TCGA_pancancer_10852whitelistsamples_68ImmuneSigs.xena&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=TCGASubtype.20170308.tsv&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=Subtype_Immune_Model_Based.txt&host=https://pancanatlas.xenahubs.net",
    "https://xenabrowser.net/datapages/?dataset=mc3.v0.2.8.PUBLIC.xena&host=https://pancanatlas.xenahubs.net",
    "",
    "",
    "",
    "",
    ""
  ),
  stringsAsFactors = FALSE
)
